version: '3.8'

services:
  docs:
    build: .
    ports:
      - "4000:4000"  # GitBook server
      - "35729:35729"  # Live reload
    volumes:
      - .:/docs
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  node_modules:
